services:
  - type: web
    name: Django-College-project
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: |
      python manage.py migrate --noinput &&
      python manage.py collectstatic --noinput &&
      gunicorn college_project.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: DJANGO_SETTINGS_MODULE
        value: college_project.settings
